### ISSUE TITLE
lazy_load plugin in demo isn't a drop-in fix

### ISSUE THREAD

**Issue by bryanbuchs** [luis-almeida/filtrify#1]
No "modern" browsers support the method that this plugin originally used; if an image is loaded on the page via the "src" attribute in the tag, that can't be suppressed -- it loads. The updated method requires that img tags use a placeholder image in the src attribute, and specify the actual image via a "data-src" attribute.

**Comment by luis-almeida** [comment]
But that's what is being done in the lazyload demo:

&lt;img src="film.png" data-original="img/movies/BladeRunner.jpg" /&gt;

"film.png" is just a "loader" image. Something to be displayed while the original image loads.

The other demos aren't using lazyload.

**Comment by bryanbuchs** [comment]
My bad. Sorry!

**Comment by luis-almeida** [comment]
Thanks anyway :)
