### ISSUE TITLE
Filter by input/search capability

### ISSUE THREAD

**Issue by mellm0** [luis-almeida/filtrify#2]
Great plugin by the way! Was wondering if there was any future plans of implementing filtering by input box (ie. search capability)

**Comment by luis-almeida** [comment]
Hey, Thanks!

I'm sorry but it's not part of my plans for future releases.
But if you also need that feature, there's a lot of good plugins for that. 

Here's an example of a good one:
http://orderedlist.com/blog/articles/live-search-with-quicksilver-style-for-jquery/

And also John Resig's version of it:
http://ejohn.org/blog/jquery-livesearch/

I wanna keep filtrify simple and minimalism. 
For the next release I wanna add some more key bindings and also make it responsive and mobile friendly.

Thanks for your feedback!
