### ISSUE TITLE
Filter “or” instead of “and”

### ISSUE THREAD

**Issue by HTMHell** [luis-almeida/filtrify#47]
Basicly I want that if I choose multiple values from one parent, it'll filter them with "OR". For example: if I choose "genre: action, comedy" It'll show all the movies with action OR comedy, and not action AND comedy.

Here is a link for my stackoverflow question, if it's not understood:
http://stackoverflow.com/questions/20933606/jquery-filtrify-plugin-filter-or-instead-of-and

Can you add this feature?

**Comment by topdotter** [comment]
Did the answer over at stackoverflow work? I'm still trying to understand some of the terser methods that have multiple non-descriptive variables. Ideally, I'd like to specify that some filters are AND and some are OR.

**Comment by imoutsatsos** [comment]
I have the same issue. The inability to do OR filtering with 'filtrify' is a show stopper for what I'm trying to do.
Nonetheless, I really appreciate your work! Best regards
Ioannis
