### ISSUE TITLE
Isotope/Masonry Integration

### ISSUE THREAD

**Issue by taitems** [luis-almeida/filtrify#7]
Integrating this script with Isotope or Masonry means you could leverage some pretty sexy UI conventions.

There's a risk it's delivering duplicate functionality, as per this [filtering example](http://isotope.metafizzy.co/demos/filtering.html).

The main benefit of at least using Masonry would involve getting rid of the mismatched heights in the movies demos, as Masonry equalises them.

**Comment by luis-almeida** [comment]
This is definitely something I want to in include in future releases.
For the first release I just wanted it to be very intuitive to use and also "developer friendly" or easy to set up if you prefer :)
I'm not sure yet what is going to be the next step but I really think I should go for mobile support first.
What do you think?
